package com.myspace.bookdemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Book implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "BOOK_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "BOOK_ID_SEQ", name = "BOOK_ID_GENERATOR")
	private java.lang.Long id;

	private java.lang.String bName;

	@javax.persistence.ManyToMany(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	private java.util.Collection<com.myspace.bookdemo.Author> authorName;

	public Book() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getbName() {
		return this.bName;
	}

	public void setbName(java.lang.String bName) {
		this.bName = bName;
	}

	public java.util.Collection<com.myspace.bookdemo.Author> getAuthorName() {
		return this.authorName;
	}

	public void setAuthorName(
			java.util.Collection<com.myspace.bookdemo.Author> param) {
		this.authorName = param;
	}

	public Book(java.lang.Long id, java.lang.String bName,
			java.util.Collection<com.myspace.bookdemo.Author> authorName) {
		this.id = id;
		this.bName = bName;
		this.authorName = authorName;
	}

}