package com.myspace.employeedpt;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "DEPARTMENT")
public class Department implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "DEPARTMENT_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "DEPARTMENT_ID_SEQ", name = "DEPARTMENT_ID_GENERATOR")
	@javax.persistence.Column(name = "DEPARTMENT_ID")
	@org.kie.api.definition.type.Position(0)
	private java.lang.Long id;

	@javax.persistence.Column(name = "DEPARTMENT_NAME")
	@org.kie.api.definition.type.Position(1)
	private java.lang.String name;

	public Department() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public Department(java.lang.Long id, java.lang.String name) {
		this.id = id;
		this.name = name;
	}

}