package com.myspace.employeedpt;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "EMPLOYEE")
public class Employee implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "EMPLOYEE_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "EMPLOYEE_ID_SEQ", name = "EMPLOYEE_ID_GENERATOR")
	@javax.persistence.Column(name = "EMPLOYEE_ID")
	private java.lang.Long id;

	@javax.persistence.Column(name = "EMPLOYEE_NAME")
	private java.lang.String ename;

	@javax.persistence.Column(name = "SALARY")
	private float salary;

	@javax.persistence.ManyToOne(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	@javax.persistence.JoinColumn(name = "DEPARTMENT_ID")
	private com.myspace.employeedpt.Department department;

	public Employee() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getEname() {
		return this.ename;
	}

	public void setEname(java.lang.String ename) {
		this.ename = ename;
	}

	public float getSalary() {
		return this.salary;
	}

	public void setSalary(float salary) {
		this.salary = salary;
	}

	public com.myspace.employeedpt.Department getDepartment() {
		return this.department;
	}

	public void setDepartment(com.myspace.employeedpt.Department department) {
		this.department = department;
	}

	public Employee(java.lang.Long id, java.lang.String ename, float salary,
			com.myspace.employeedpt.Department department) {
		this.id = id;
		this.ename = ename;
		this.salary = salary;
		this.department = department;
	}

}