package com.myspace.new_timesheet;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "PROJECTTASK")
public class ProjectTask implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PROJECTTASK_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "PROJECTTASK_ID_SEQ", name = "PROJECTTASK_ID_GENERATOR")
	@javax.persistence.Column(name = "TASK_ID")
	@org.kie.api.definition.type.Position(0)
	private java.lang.Long id;

	@javax.persistence.Column(name = "BUDGETHRS")
	@org.kie.api.definition.type.Position(value = 1)
	private java.lang.String budgetHr;

	public ProjectTask() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getBudgetHr() {
		return this.budgetHr;
	}

	public void setBudgetHr(java.lang.String budgetHr) {
		this.budgetHr = budgetHr;
	}

	public ProjectTask(java.lang.Long id, java.lang.String budgetHr) {
		this.id = id;
		this.budgetHr = budgetHr;
	}

}