package com.myspace.new_timesheet;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Project implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PROJECT_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "PROJECT_ID_SEQ", name = "PROJECT_ID_GENERATOR")
	@org.kie.api.definition.type.Position(0)
	@javax.persistence.Column(name = "PROJECT_ID")
	private java.lang.Long id;

	@javax.persistence.Column(name = "PROJECT_NAME")
	@org.kie.api.definition.type.Position(value = 1)
	private java.lang.String projectName;

	@javax.persistence.Column(name = "BUDGET_REQUESTED")
	@org.kie.api.definition.type.Position(value = 2)
	private java.lang.Float budgetRequested;

	@javax.persistence.Column(name = "STARTDATE")
	@org.kie.api.definition.type.Position(value = 3)
	private java.util.Date startDate;

	@javax.persistence.Column(name = "ENDDATE")
	@org.kie.api.definition.type.Position(value = 4)
	private java.util.Date endDate;

	@javax.persistence.OneToMany(fetch = javax.persistence.FetchType.EAGER, targetEntity = ProjectTask.class, cascade = {javax.persistence.CascadeType.ALL})
	@org.kie.api.definition.type.Position(value = 5)
	private java.util.List<com.myspace.new_timesheet.ProjectTask> task_id;

	public Project() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(java.lang.String projectName) {
		this.projectName = projectName;
	}

	public java.lang.Float getBudgetRequested() {
		return this.budgetRequested;
	}

	public void setBudgetRequested(java.lang.Float budgetRequested) {
		this.budgetRequested = budgetRequested;
	}

	public java.util.Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(java.util.Date startDate) {
		this.startDate = startDate;
	}

	public java.util.Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(java.util.Date endDate) {
		this.endDate = endDate;
	}

	public java.util.List<com.myspace.new_timesheet.ProjectTask> getTask_id() {
		return this.task_id;
	}

	public void setTask_id(
			java.util.List<com.myspace.new_timesheet.ProjectTask> task_id) {
		this.task_id = task_id;
	}

	public Project(java.lang.Long id, java.lang.String projectName,
			java.lang.Float budgetRequested, java.util.Date startDate,
			java.util.Date endDate,
			java.util.List<com.myspace.new_timesheet.ProjectTask> task_id) {
		this.id = id;
		this.projectName = projectName;
		this.budgetRequested = budgetRequested;
		this.startDate = startDate;
		this.endDate = endDate;
		this.task_id = task_id;
	}

}